name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    uses: isaacoluwade/mtkp-platform-actions/.github/workflows/terraform-module-ci.yml@main
    with:
      terratest_timeout_minutes: 15
      aws_dr_region: us-west-2
    secrets:
      AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
